application/urls.py
from django.conf.urls import patterns, include, url
from application.views import *
from application.datas import *


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'python_brain_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', index),
    url(r'hello/', hello),
    url(r'member/save/', member_save),
    url(r'member/show/', member_show),
    url(r'member/(?P<member_id>\d+)/', member_detail, name="detail"),
)

python_brain_django/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

# if DEBUG is True, this will never be used
handler404 = 'application.views.page_not_found'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'python_brain_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^application/', include('application.urls', namespace="application")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
)

application/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    # 用户名，登录账号
    username = models.CharField(max_length=50)
    # 全名
    fullname = models.CharField(max_length=50)
    # 头像
    avatar = models.CharField(max_length=200)

    # On Python 3
    def __str__(self):
        return self.fullname
    # On Python 2
    def __unicode__(self):
        return self.fullname

application/views.py
from django.shortcuts import render_to_response, get_object_or_404
import datetime
from application.models import Member

# Create your views here.

def hello(request):
    now = datetime.datetime.now()
    return render_to_response("hello.html", {"currentTime":now})

def page_not_found(request):
    return render_to_response("404.html")

def index(request):
    recent_members = Member.objects.order_by("username")[:5]
    [print(member) for member in recent_members]
    return render_to_response("application/index.html", {"recent_members": recent_members})

def member_detail(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    return render_to_response("application/detail.html", {"member": member})

application/templates/application/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>index</title>
    {% load staticfiles %}
    {% comment %}<link rel="stylesheet" href="/static/css/default-new.css"/>{% endcomment %}
    <link rel="stylesheet" href="{% static 'css/default-new.css' %}"/>
</head>
<body>
    <section class="hero-wrapper scroll-effect full-width-container container" data-scroll-effect-type="parallax">
        <div class="scroll-effect-layer hero-area hero-home" data-parallax-effect="vertical" data-parallax-offset-x="0" data-parallax-offset-y="-80" data-parallax-speed="2" style="background-image: url('{% static "images/spotlights/home.jpg" %}'); background-position: 0px 20px;">
          <div class="hero-inner-shadow"></div>
          <p class="hero-photo-credit">
            Global Impact Awardee, SolarAid, is bringing solar lighting to rural communities.
          </p>
        </div>
        <div class="maia-aux">
          <div class="maia-cols"></div>
        </div>
    </section>

    <section class="spotlight-area">
        <div class="maia-aux">
          <h2>
            member<strong>detail</strong>
          </h2>
          <div class="maia-cols">
            <div class="maia-col-4">
                <ul>
                    {% if member %}
                        <li>pk: {{ member.pk }}</li>
                        <li>username: {{ member.username }}</li>
                        <li>fullname: {{ member.fullname }}</li>
                        <li>avatar: {{ member.avatar }}</li>
                    {% endif %}
                </ul>
            </div>
          </div>
        </div>
    </section>

</body>
</html>

application/templates/application/index.html
<!DOCTYPE html>
<html>
<head>
    <title>index</title>
    {% load staticfiles %}
    {% comment %}<link rel="stylesheet" href="/static/css/default-new.css"/>{% endcomment %}
    <link rel="stylesheet" href="{% static 'css/default-new.css' %}"/>
</head>
<body>
    <section class="hero-wrapper scroll-effect full-width-container container" data-scroll-effect-type="parallax">
        <div class="scroll-effect-layer hero-area hero-home" data-parallax-effect="vertical" data-parallax-offset-x="0" data-parallax-offset-y="-80" data-parallax-speed="2" style="background-image: url('{% static "images/spotlights/home.jpg" %}'); background-position: 0px 20px;">
          <div class="hero-inner-shadow"></div>
          <p class="hero-photo-credit">
            Global Impact Awardee, SolarAid, is bringing solar lighting to rural communities.
          </p>
        </div>
        <div class="maia-aux">
          <div class="maia-cols"></div>
        </div>
    </section>

    <section class="spotlight-area">
        <div class="maia-aux">
          <h2>
            recent<strong>members</strong>
          </h2>
          <div class="maia-cols">
            <div class="maia-col-4">
                <ul>
                    {% if recent_members %}
                        {% for member in recent_members %}
                            <li><a href="{% url 'application:detail' member.id %}">{{ member.fullname }}</a></li>
                        {% endfor %}
                        {% else %}
                        <p>there is no member available</p>
                    {% endif %}
                </ul>
            </div>
          </div>
        </div>
    </section>

</body>
</html>

application/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
    <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
    <title>{% block title %} python brain {% endblock %}</title>
    {% block staticResource %}{% endblock %}
</head>
<body>
    {% block body %} hello world! {% endblock %}
</body>
</html>

application/templates/hello.html
{% extends "base.html" %}
{% block title %}
    hello page
{% endblock %}
{% block body %}
    这是你MD body 歌妹呀
{% endblock %}

application/templates/hello11.html
{% extends "base.html" %}
{% block title %}
    hello page
{% endblock %}
<!DOCTYPE html>
<html>
<head>
    <title>time</title>
    {% load staticfiles %}
    {% comment %}<link rel="stylesheet" href="/static/css/default-new.css"/>{% endcomment %}
    <link rel="stylesheet" href="{% static 'css/default-new.css' %}"/>
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
    <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
</head>
<body>
    <section class="hero-wrapper scroll-effect full-width-container container" data-scroll-effect-type="parallax">
        <div class="scroll-effect-layer hero-area hero-home" data-parallax-effect="vertical" data-parallax-offset-x="0" data-parallax-offset-y="-80" data-parallax-speed="2" style="background-image: url('{% static "images/spotlights/home.jpg" %}'); background-position: 0px 20px;">
          <div class="hero-inner-shadow"></div>
          <p class="hero-photo-credit">
            Global Impact Awardee, SolarAid, is bringing solar lighting to rural communities.
          </p>
        </div>
        <div class="maia-aux">
          <div class="maia-cols"></div>
        </div>
    </section>
<div style="height: 40px;">
it is now {{ currentTime }}!
</div>

   <section>
        <div class="maia-aux">
          <div class="maia-cols">
            <div class="maia-col-6 hero-content">
              <div class="hero-content-wrapper">
                <h1>
                  A better world, faster.
                </h1>
                <p class="hero-introduction">
                  Tech entrepreneurs are using innovation to tackle some of the world’s biggest
                  challenges. We invest in teams with bold ideas that create lasting global impact.
                </p>
              </div>
            </div>
          </div>
        </div>
  </section>

<section class="spotlight-area">
        <div class="maia-aux">
          <h2>
            Spot<strong>lights</strong>
          </h2>
          <div class="maia-cols">
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./spotlights#content-giving-through-glass">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Giving Through Glass" src="{% static 'images/spotlights/home-glass-program.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Giving Through Glass
                  </figcaption>
                </div>
              </figure></a>
            </div>
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./global-impact-awards/challenge/#content-australia">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Launching Impact Challenge in Australia" src="{% static 'images/spotlights/home-impact-challenge-australia.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Launching Impact Challenge in Australia
                  </figcaption>
                </div>
              </figure></a>
            </div>
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./spotlights#content-improving-computer-science-education">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Improving Computer Science Education" src="{% static 'images/spotlights/home-computer-science.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Improving Computer Science Education
                  </figcaption>
                </div>
              </figure></a>
            </div>
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./global-impact-awards/challenge/#content-bay-area">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Supporting Bay Area Nonprofits" src="{% static 'images/spotlights/home-supporting-bay-area-nonprofits.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Supporting Bay Area Nonprofits
                  </figcaption>
                </div>
              </figure></a>
            </div>
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./spotlights#content-empowering-women-and-girls">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Empowering Women &amp; Girls" src="{% static 'images/spotlights/home-women-and-girls.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Empowering Women &amp; Girls
                  </figcaption>
                </div>
              </figure></a>
            </div>
            <div class="maia-col-4">
              <a class="shadow curved-shadow" href="./spotlights#content-fighting-human-trafficking-and-child-abuse">
              <figure>
                <div class="spotlight-img-wrapper">
                  <img alt="Fighting Trafficking and Child Abuse" src="{% static 'images/spotlights/home-trafficking-slavery.jpg' %}">
                </div>
                <div class="caption-wrapper">
                  <figcaption>
                    Fighting Trafficking and Child Abuse
                  </figcaption>
                </div>
              </figure></a>
            </div>
          </div>
        </div>
      </section>

</body>
</html>